# Generated by Django 3.1 on 2020-09-23 01:16

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20200907_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='address',
            field=models.CharField(max_length=140, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='room',
            name='baths',
            field=models.IntegerField(verbose_name='baths'),
        ),
        migrations.AlterField(
            model_name='room',
            name='bedrooms',
            field=models.IntegerField(verbose_name='bedrooms'),
        ),
        migrations.AlterField(
            model_name='room',
            name='beds',
            field=models.IntegerField(verbose_name='beds'),
        ),
        migrations.AlterField(
            model_name='room',
            name='check_in',
            field=models.TimeField(verbose_name='check_in'),
        ),
        migrations.AlterField(
            model_name='room',
            name='check_out',
            field=models.TimeField(verbose_name='check_out'),
        ),
        migrations.AlterField(
            model_name='room',
            name='city',
            field=models.CharField(max_length=80, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='room',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='room',
            name='guests',
            field=models.IntegerField(verbose_name='guest'),
        ),
        migrations.AlterField(
            model_name='room',
            name='instant_book',
            field=models.BooleanField(default=False, verbose_name='instant_book'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=140, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.IntegerField(verbose_name='price'),
        ),
    ]
